### ISSUE TITLE
Log out when orientation changed

### ISSUE THREAD

**Issue by likhongomes** [Capstone-Projects-2020-Spring/iASL-iOS#31]
Currently the user gets logged out and prompted to log back in when the orientation of the device is changed. I just tested it on iPad. Don't know if this issue exists for iPhone

**Comment by ApplebaumIan** [comment]
> Currently the user gets logged out and prompted to log back in when the orientation of the device is changed. I just tested it on iPad. Don't know if this issue exists for iPhone

This issue is not in master

**Comment by likhongomes** [comment]
fixed
